# 1. Dùng bản Python nhẹ nhưng đủ dùng
FROM python:3.13-slim

# 2. Cài đặt các thư viện hệ thống mà OpenCV bắt buộc phải có
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# 3. Tạo thư mục làm việc trong thùng container
WORKDIR /app

# 4. Copy danh sách thư viện và cài đặt (làm bước này trước để tận dụng cache)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copy toàn bộ code dự án vào
COPY . .

# 6. Mở cổng 8000 cho FastAPI
EXPOSE 8000

# 7. Lệnh khởi chạy
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]